services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: maintenance-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin@2026"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    volumes:
      - maintenance_sqldata:/var/opt/mssql
    restart: unless-stopped

volumes:
  maintenance_sqldata:
